version: '3'
services:
  barcode-reader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
    command: ["python", "./src/barcode_reader.py"]

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
    command: ["pytest", "tests"]
